version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_PASSWORD_ROOT: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3304:3304"
    volumes:
      - blog_data:/var/lib/mysql
volumes:
  blog_data: